# Generated by Django 5.1.3 on 2024-11-30 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lock_system_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesslog',
            old_name='timestamp',
            new_name='access_time',
        ),
        migrations.RenameField(
            model_name='accesslog',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='rfiduser',
            old_name='name',
            new_name='username',
        ),
    ]
