# Generated by Django 5.1.3 on 2024-12-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock_system_app', '0002_rename_timestamp_accesslog_access_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='rfid_tag',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rfiduser',
            name='rfid_tag',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
