# Generated by Django 5.1.3 on 2024-12-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock_system_app', '0003_accesslog_rfid_tag_alter_accesslog_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='rfid_tag',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rfiduser',
            name='rfid_tag',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
